apiVersion: v1
kind: PersistentVolume
metadata:
  name: wordpress-pv
spec:
  storageClassName: local-storage
  claimRef:
    name: wordpress-volume
    namespace: default
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  local:
    path: /data
  nodeAffinity:
   required:
    nodeSelectorTerms:
    - matchExpressions:
      - key: kubernetes.io/hostname
        operator: In
        values:
        - minikube