apiVersion: v1
kind: PersistentVolume
metadata:
  name: wp-pv-mk
spec:
  storageClassName: wp-local-storage
  claimRef:
    name: worpress-volume
    namespace: default
  capacity: 
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  local:
    path: /mnt
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - minikube
          