apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-volume
  namespace: default
spec:
  accessModes:
   - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: standard-rwo


