apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: wordpress-pd-gke
provisioner: pd.csi.storage.gke.io
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
parameters:
  type: pd-balanced